### ISSUE TITLE
How do you instal this module

### ISSUE THREAD

**Issue by cpe111** [dev7355608/gm-vision#1]
Th manifest link is broken - I get 
`Error: Unable to load valid world manifest data from "https://github.com/dev7355608/gm-vision/blob/main/module.json"
The requested manifest at "https://github.com/dev7355608/gm-vision/blob/main/module.json" did not provide world manifest data.
    at Module.installPackage (file:///home/foundry/foundryvtt/resources/app/dist/packages/views.mjs:1:1634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SetupView.handlePost (file:///home/foundry/foundryvtt/resources/app/dist/server/views/setup.mjs:1:1980)
error @ setup.js:292
`

When trying to load the manifest file from https://foundryvtt.com/packages/gm-vision

**Comment by dev7355608** [comment]
Right-Click -> Copy Link Address on the Manifest URL gives me https://github.com/dev7355608/gm-vision/releases/download/v1.0.1/module.json, which is the correct one. I have no idea how you ended up with the other URL. Did you have no success installing this module via the package manager in Foundry?

**Comment by dev7355608** [comment]
I assume you have been able to install the module by now. If not, let me know.
