### ISSUE TITLE
Any chance there could be a button on the sidebar to enable and disable the feature?

### ISSUE THREAD

**Issue by Samulady** [dev7355608/gm-vision#4]
Basically title.

I hate using hot keys, I'm horribly forgetful and will either just forget the hotkey or forget I have the feature, haha. Just an added button in the lighting hotbar would be incredible for added accessibility.

**Comment by SLinxTheFox** [comment]
+1, i WILL forget i even have this module, so while i hate side button bloat, i sorta need some sort of visual reminder that this mod exists

**Comment by Oryan77** [comment]
+1 Same here. The "Less Fog" module does something similar to this module and has a side button under the Token Controls sidebar which is very useful. This module is much better though and all it's missing is that button.

**Comment by dev7355608** [comment]
To avoid button bloat I made right-clicking the lighting controls button toggle GM Vision (v1.1.0).
