### ISSUE TITLE
3D Canvas

### ISSUE THREAD

**Issue by makinava** [dev7355608/gm-vision#7]
Don't work with 3d canvas addon

**Comment by dev7355608** [comment]
Are there errors in the console (F12 -> Console tab)? This module won't affect the 3D view, in case that is what your expecting.

**Comment by makinava** [comment]
There is not erros in console. The bulb icon turns on and off correctly, but the illumination for GM not change. Deactivating 3D works fine

**Comment by dev7355608** [comment]
Very likely needs changes on 3D Canvas side. If this is still an issue. Not sure if this issue was reported for V11 or V12. Closing because stale.
