### ISSUE TITLE
2.0 Versioning Overlap

### ISSUE THREAD

**Issue by corhean** [dev7355608/gm-vision#9]
Newest update indicates compatibility with v13 (which is currently not stable), but does not indicate if it is also backwards compatible with v12, causing a warning for any updates.

If 2.0 is compatible with v12, the versioning should indicate this to ensure the auto-updater works as expected with no errors.

![image](https://github.com/user-attachments/assets/b06f8abe-7758-4140-9821-4a31f07a00a5)

**Comment by dev7355608** [comment]
GM Vision 2.0 is not V13 compatible. The warning you see is expected. That's how Foundry present the information that a newer version of a module is available, but it cannot be installed because of the minimum version requirement.
